name       : perl-test2-suite
version    : '0.000122'
release    : 9
source     :
    - https://github.com/Test-More/Test2-Suite/archive/v0.000122.tar.gz : fcb0c9a8b41b7b97b0b499dc29128f0063d9e91051119004334f85014552b7ab
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test2::Suite - Distribution with a rich set of tools built upon the Test2 framework.
homepage   : https://github.com/Test-More/Test2-Suite
description: |
    Rich set of tools, plugins, bundles, etc built upon the Test2 testing library. If you are interested in writing tests, this is the distribution for you.
builddeps  :
    - perl-importer
    - perl-module-pluggable
    - perl-scalar-list-utils
    - perl-scope-guard
    - perl-sub-info
    - perl-term-table
    - perl-test-simple
    - perl-time-hires
    - perl-sub-name
    - perl-term-readkey
    - perl-unicode-linebreak
    - perl-term-size-any
rundeps    :
    - perl-importer
    - perl-module-pluggable
    - perl-scalar-list-utils
    - perl-scope-guard
    - perl-sub-info
    - perl-term-table
    - perl-test-simple
    - perl-time-hires
    - perl-sub-name
    - perl-term-readkey
    - perl-unicode-linebreak
    - perl-term-size-any
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
