name       : perl-test2-suite
version    : '0.000155'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test2-Suite-0.000155.tar.gz : c78e6bc4d69bc097836976863382b52b9e0c31ee185066ce60c54bd74baad53d
homepage   : https://metacpan.org/dist/Test2-Suite
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test2::Suite - Distribution with a rich set of tools built upon the Test2 framework
description: |
    Rich set of tools, plugins, bundles, etc built upon the Test2 testing library. If you are interested in writing tests, this is the distribution for you.
builddeps  :
    - perl-importer
    - perl-module-pluggable
    - perl-scalar-list-utils
    - perl-scope-guard
    - perl-sub-info
    - perl-term-table
    - perl-test-simple
    - perl-time-hires
    - perl-sub-name
    - perl-term-readkey
    - perl-unicode-linebreak
    - perl-term-size-any
rundeps    :
    - perl-importer
    - perl-module-pluggable
    - perl-scalar-list-utils
    - perl-scope-guard
    - perl-sub-info
    - perl-term-table
    - perl-test-simple
    - perl-time-hires
    - perl-sub-name
    - perl-term-readkey
    - perl-unicode-linebreak
    - perl-term-size-any
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
