name       : perl-test2-suite
version    : '0.000100'
release    : 2
source     :
    - https://github.com/Test-More/Test2-Suite/archive/v0.000100.tar.gz : 3f44102f4d82a5e1793b61b44a3d6c640b2118153e10ec55b35f352d72c17240
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test2::Suite - Distribution with a rich set of tools built upon the Test2 framework.
description: |
    Rich set of tools, plugins, bundles, etc built upon the Test2 testing library. If you are interested in writing tests, this is the distribution for you.
builddeps  :
    - perl-importer
    - perl-module-pluggable
    - perl-scalar-list-utils
    - perl-scope-guard
    - perl-sub-info
    - perl-term-table
    - perl-test-simple
    - perl-time-hires
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
